py=./configTool
SCRIPTS=./scripts
CONFIG_DIR=./conf

ConfigTool_js_DIR=./configTool/static/js/conf
ConfigTool_DIR=./configTool

Cct_NAME=configtool

# monitoring
monitoringIP=192.168.100.201
monitoringPort=8088

# ice
iceIP=192.168.100.170
icePort=10010
